# Generated by Django 5.2.3 on 2025-06-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
