# Generated by Django 5.2.3 on 2025-06-18 11:06

import cloudinary.models
import user_accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0003_remove_profile_account_number_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(
                default=18, validators=[user_accounts.validators.validate_age]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
