# Generated by Django 5.2.3 on 2025-06-18 11:07

import user_accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0004_alter_profile_age_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(
                validators=[user_accounts.validators.validate_age]
            ),
        ),
    ]
