# Generated by Django 5.2.3 on 2025-06-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0006_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
