# Generated by Django 5.2.3 on 2025-06-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0007_alter_account_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sender_transaction",
                to="user_accounts.account",
            ),
        ),
    ]
