# Generated by Django 5.2.3 on 2025-06-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0008_alter_transaction_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="reciever",
            new_name="receiver",
        ),
    ]
