# Generated by Django 5.2.3 on 2025-06-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0009_rename_reciever_transaction_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiver_transaction",
                to="user_accounts.account",
            ),
        ),
    ]
