# Generated by Django 5.2.3 on 2025-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0010_alter_transaction_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
